scene_name: munich
deployment: elaa_m
frequency: 28000000000.0
bandwidth: 200000000.0
num_subcarriers: 1584
guard_band_ratio: 0.1
numerology_mu: 3
temperature: 293.0
tx_rows: 32
tx_cols: 16
tx_polarization: V
rx_rows: 1
rx_cols: 1
rx_polarization: cross
num_bs: 4
power_dbm: 40.0
bs_positions:
- - -123.666
  - 169.171
  - 16.711
- - 122.398
  - -296.02
  - 12.964
- - -140.037
  - -296.619
  - 14.8
- - 119.532
  - 161.534
  - 17.841
synthetic_array: true
max_depth: 5
max_num_paths_per_src: 100000
samples_per_src: 100000
num_ue: 100
sinr_min_db: 2.0
sinr_max_db: 40.0
dist_min: 10.0
dist_max: 150.0
ue_device_types:
- - 1
  - 1
  - cross
- - 1
  - 2
  - V
- - 2
  - 2
  - V
data_dir: assets/data/channels_elaa_m_1k_28g
num_snapshots: 100
train_bs_ids:
- 1
- 2
val_bs_ids:
- 0
test_bs_ids:
- 3
